package com.example.myapplication;

import java.util.ArrayList;

public class ProvinceData {

    public static int[] jmlKota = {
            5,
            33,
            7,
            2,
            2,
            4,
            1,
            2,
            1,
            1,
            5,
            9,
            6,
            1,
            9,
            4,
            1,
            1,
            2,
            2,
            1,
            2,
            3,
            1,
            4,
            1,
            3,
            2,
            1,
            0,
            2,
            2,
            1,
            1
    };
    public static String[] provinceDetails = {"Aceh (Aksara Jawoë : اچيه دارالسلام) adalah sebuah provinsi di Indonesia yang ibu kotanya berada di Banda Aceh. Aceh merupakan salah satu provinsi di Indonesia yang diberi status sebagai daerah istimewa dan juga diberi kewenangan otonomi khusus. Aceh terletak di ujung utara pulau Sumatra dan merupakan provinsi paling barat di Indonesia. Menurut hasil sensus Badan Pusat Statistik tahun 2019, jumlah penduduk provinsi ini sekitar 5.281.891Jiwa.[10] Letaknya dekat dengan Kepulauan Andaman dan Nikobar di India dan terpisahkan oleh Laut Andaman. Aceh berbatasan dengan Teluk Benggala di sebelah utara, Samudra Hindia di sebelah barat, Selat Malaka di sebelah timur, dan Sumatra Utara di sebelah tenggara dan selatan.\n",
            "Sumatra Utara (disingkat Sumut) adalah sebuah provinsi di Indonesia yang terletak di bagian utara Pulau Sumatra. Provinsi ini beribu kota di Medan.\n",
            "Sumatra Barat (disingkat Sumbar) adalah sebuah provinsi di Indonesia yang terletak di Pulau Sumatra dengan Padang sebagai ibu kotanya. Provinsi Sumatra Barat terletak sepanjang pesisir barat Sumatra bagian tengah, dataran tinggi Bukit Barisan di sebelah timur, dan sejumlah pulau di lepas pantainya seperti Kepulauan Mentawai. Dari utara ke selatan, provinsi dengan wilayah seluas 42.297,30 km² ini berbatasan dengan empat provinsi, yakni Sumatra Utara, Riau, Jambi, dan Bengkulu.\n",
            "Riau (Jawi: رياو) adalah sebuah provinsi di Indonesia yang terletak di bagian tengah pulau Sumatra. Provinsi ini terletak di bagian tengah pantai timur Pulau Sumatra, yaitu di sepanjang pesisir Selat Melaka. Hingga tahun 2004, provinsi ini juga meliputi Kepulauan Riau, sekelompok besar pulau-pulau kecil (pulau-pulau utamanya antara lain Pulau Batam dan Pulau Bintan) yang terletak di sebelah timur Sumatra dan sebelah selatan Singapura. Kepulauan ini dimekarkan menjadi provinsi tersendiri pada Juli 2004. Ibu kota dan kota terbesar Riau adalah Pekanbaru. Kota besar lainnya antara lain Dumai, Selatpanjang, Bagansiapiapi, Bengkalis, Bangkinang, Tembilahan, dan Rengat.\n",
            "Jambi (Jawi: جامبي) adalah sebuah Provinsi Indonesia yang terletak di pesisir timur di bagian tengah Pulau Sumatra. Jambi adalah satu dari tiga provinsi di Indonesia yang ibu kotanya bernama sama dengan nama provinsinya, selain Bengkulu, Daerah Khusus Ibukota Jakarta, dan Gorontalo.\n",
            "Sumatra Selatan (umumnya disingkat menjadi Sumsel) adalah provinsi di Indonesia yang terletak di bagian selatan Pulau Sumatra. Provinsi ini beribukota di Palembang. Secara geografis, Sumatra Selatan berbatasan dengan provinsi Jambi di utara, provinsi Kep. Bangka-Belitung di timur, provinsi Lampung di selatan dan Provinsi Bengkulu di barat. Provinsi ini kaya akan sumber daya alam, seperti minyak bumi, gas alam dan batu bara. Selain itu ibu kota provinsi Sumatra Selatan, Palembang, telah terkenal sejak dahulu karena menjadi pusat Kerajaan Sriwijaya.\n",
            "Bengkulu (bahasa Inggris: Bencoolen, Aks. Rejang: ꤷꥍꤲ꥓ꤰꥈꤾꥈ) adalah sebuah provinsi di Indonesia. Ibu kotanya berada di Kota Bengkulu. Provinsi ini terletak di bagian barat daya Pulau Sumatra.\n",
            "Lampung (Aksara Lampung: ) adalah sebuah provinsi paling selatan di Pulau Sumatra, Indonesia, dengan ibu kota Bandar Lampung. Provinsi ini memiliki dua kota yaitu Kota Bandar Lampung dan Kota Metro serta 13 kabupaten. Posisi Lampung secara geografis berada di sebelah barat berbatasan dengan Samudra Hindia, di sebelah timur dengan Laut Jawa, di sebelah utara berbatasan dengan provinsi Sumatra Selatan, dan di sebelah selatan berbatasan dengan Selat Sunda.\n",
            "Provinsi Kepulauan Bangka Belitung (disingkat Babel) adalah sebuah provinsi di Indonesia yang terdiri dari dua pulau utama yaitu Pulau Bangka dan Pulau Belitung serta ratusan pulau-pulau kecil, total pulau yang telah bernama berjumlah 470 buah dan yang berpenghuni hanya 50 pulau. Bangka Belitung terletak di bagian timur Pulau Sumatra, dekat dengan Provinsi Sumatra Selatan. Bangka Belitung dikenal sebagai daerah penghasil timah, memiliki pantai yang indah dan kerukunan antar etnis. Ibu kota provinsi ini ialah Pangkalpinang. Pemerintahan provinsi ini disahkan pada tanggal 9 Februari 2001. Setelah dilantiknya Pj. Gubernur yakni H. Amur Muchasim, SH (mantan Sekjen Depdagri) yang menandai dimulainya aktivitas roda pemerintahan provinsi.\n",
            "Kepulauan Riau (disingkat Kepri) adalah sebuah provinsi di Indonesia. Provinsi Kepulauan Riau berbatasan dengan Vietnam dan Kamboja di sebelah utara; Malaysia dan provinsi Kalimantan Barat di timur; provinsi Kepulauan Bangka Belitung dan Jambi di selatan; Negara Singapura, Malaysia dan provinsi Riau di sebelah barat. Provinsi ini termasuk provinsi kepulauan di Indonesia.\n",
            "Daerah Khusus Ibukota Jakarta (DKI Jakarta) adalah ibu kota negara dan kota terbesar di Indonesia. Jakarta merupakan satu-satunya kota di Indonesia yang memiliki status setingkat provinsi. Jakarta terletak di pesisir bagian barat laut Pulau Jawa. Dahulu pernah dikenal dengan beberapa nama di antaranya Sunda Kelapa, Jayakarta, dan Batavia. Di dunia internasional Jakarta juga mempunyai julukan J-Town,[8] atau lebih populer lagi The Big Durian karena dianggap kota yang sebanding New York City (Big Apple) di Indonesia.\n",
            "Jawa Barat (disingkat Jabar, aksara Sunda: ᮏᮝ ᮊᮥᮜᮧᮔ᮪, Cacarakan: ꦗꦮ ꦏꦸꦭꦵꦤ꧀, Sunda dan Cirebon: Jawa Kulon) adalah sebuah provinsi di Indonesia, ibu kotanya berada di Bandung.\n",
            "Jawa Tengah (disingkat Jateng) (Hanacaraka: ꦗꦮ ꦠꦼꦔꦃ; Jawa: Jåwå Tengah) adalah sebuah provinsi Indonesia yang terletak di bagian tengah Pulau Jawa. Ibu kotanya adalah Semarang. Provinsi ini berbatasan dengan Provinsi Jawa Barat di sebelah barat, Samudra Hindia dan Daerah Istimewa Yogyakarta di sebelah selatan, Jawa Timur di sebelah timur, dan Laut Jawa di sebelah utara. Luas wilayahnya 32.548 km², atau sekitar 28,94% dari luas pulau Jawa. Provinsi Jawa Tengah juga meliputi Pulau Nusakambangan di sebelah selatan (dekat dengan perbatasan Jawa Barat), serta Kepulauan Karimun Jawa di Laut Jawa.\n",
            "Daerah Istimewa Yogyakarta (bahasa Jawa: ꦝꦲꦺꦫꦃ ꦆꦱ꧀ꦠꦶꦩꦺꦮ ꦔꦪꦺꦴꦒꦾꦏꦂꦠ, translit. Dhaérah Istiméwa Ngayogyakarta) adalah Daerah Istimewa setingkat provinsi di Indonesia yang merupakan peleburan Negara Kesultanan Yogyakarta dan Negara Kadipaten Paku Alaman. Daerah Istimewa Yogyakarta terletak di bagian selatan Pulau Jawa, dan berbatasan dengan Provinsi Jawa Tengah dan Samudera Hindia. Daerah Istimewa yang memiliki luas 3.185,80 km2 ini terdiri atas satu kotamadya, dan empat kabupaten, yang terbagi lagi menjadi 78 kecamatan, dan 438 desa/kelurahan. Menurut sensus penduduk 2010 memiliki populasi 3.452.390 jiwa dengan proporsi 1.705.404 laki-laki, dan 1.746.986 perempuan, serta memiliki kepadatan penduduk sebesar 1.084 jiwa per km2.",
            "Jawa Timur (disingkat Jatim, bahasa Jawa: Hanacaraka: ꧋ꦗꦮꦮꦺꦠꦤ꧀ Pegon: جاوا ويتان, translit. Jåwå Wétan, bahasa Madura: Jhâbâh Dhimor) adalah sebuah provinsi di bagian timur Pulau Jawa, Indonesia. Ibu kotanya terletak di Surabaya. Luas wilayahnya 47.922 km², dan jumlah penduduknya 42.030.633 jiwa (sensus 2017). Jawa Timur memiliki wilayah terluas di antara 6 provinsi di Pulau Jawa, dan memiliki jumlah penduduk terbanyak kedua di Indonesia setelah Jawa Barat. Jawa Timur berbatasan dengan Laut Jawa di utara, Selat Bali di timur, Samudra Hindia di selatan, serta Provinsi Jawa Tengah di barat. Wilayah Jawa Timur juga meliputi Pulau Madura, Pulau Bawean, Pulau Kangean serta sejumlah pulau-pulau kecil di Laut Jawa (Kepulauan Masalembu), dan Samudera Hindia (Pulau Sempu, dan Nusa Barung).\n",
            "Banten (aksara Sunda: ᮘᮔ᮪ᮒᮨᮔ᮪ Hanacaraka: ꦨꦤ꧀ꦠꦼꦤ꧀; Pegon: بَنْتٓنْ）adalah sebuah provinsi ,wilayah paling barat di Pulau Jawa, Indonesia. Provinsi ini pernah menjadi bagian dari Provinsi Jawa Barat, tetapi menjadi wilayah pemekaran sejak tahun 2000, dengan keputusan Undang-Undang Nomor 23 Tahun 2000. Pusat pemerintahannya berada di Kota Serang.\n",
            "Bali adalah sebuah provinsi di Indonesia yang ibu kota provinsinya bernama Denpasar. Bali juga merupakan salah satu pulau di Kepulauan Nusa Tenggara. Di awal kemerdekaan Indonesia, pulau ini termasuk dalam Provinsi Sunda Kecil yang beribu kota di Singaraja, dan kini terbagi menjadi 3 provinsi: Bali, Nusa Tenggara Barat, dan Nusa Tenggara Timur.",
            "Nusa Tenggara Timur (disingkat NTT) adalah sebuah provinsi di Indonesia yang meliputi bagian timur Kepulauan Nusa Tenggara. Provinsi ini beribu kota di Kupang dan memiliki 22 Kabupaten/Kota.\n" +
                    "Di awal kemerdekaan Indonesia, kepulauan ini merupakan wilayah Provinsi Sunda Kecil[5][6]. yang beribu kota di kota Singaraja, kini terdiri atas 3 provinsi (berturut-turut dari barat): Bali, Nusa Tenggara Barat, dan Nusa Tenggara Timur.\n",
            "Nusa Tenggara Barat (disingkat NTB) ialah sebuah provinsi di Indonesia yang berada pada bagian barat Kepulauan Nusa Tenggara. Provinsi ini beribu kota di Mataram dan memiliki 10 Kabupaten dan Kota.\n" +
                    "Pada awal kemerdekaan Indonesia, wilayah ini termasuk dalam wilayah Provinsi Sunda Kecil[3][4] yang beribu kota di Singaraja. Kemudian, wilayah Provinsi Sunda Kecil dibagi menjadi 3 provinsi: Bali, Nusa Tenggara Barat, dan Nusa Tenggara Timur. Dua pulau terbesar di provinsi ini adalah Lombok yang terletak di barat dan Sumbawa yang terletak di timur.\n",
            "Kalimantan Barat (disingkat Kalbar) adalah sebuah provinsi di Indonesia yang terletak di Pulau Kalimantan dengan ibu kota Provinsi Kota Pontianak.[3] Luas wilayah Provinsi Kalimantan Barat adalah 146.807 km² (7,53% luas Indonesia).[4] Merupakan provinsi terluas keempat setelah Papua, Kalimantan Timur dan Kalimantan Tengah.",
            "Kalimantan Tengah (disingkat Kalteng) adalah salah satu provinsi di Indonesia yang terletak di Pulau Kalimantan. Ibu kotanya adalah Kota Palangka Raya. Kalimantan Tengah memiliki luas 157.983 km². Berdasarkan sensus tahun 2010, provinsi ini memiliki populasi 2.202.599 jiwa, yang terdiri atas 1.147.878 laki-laki dan 1.054.721 perempuan. Data BPS Kalimantan Tengah tahun 2018 menunjukkan penduduk provinsi ini tahun 2017 bertambah menjadi 2.605.274 (Laki-laki 1.361.715 jiwa dan perempuan 1.243.559 jiwa).[1] Kalimantan Tengah mempunyai 13 kabupaten dan 1 kota.\n",
            "Kalimantan Selatan (disingkat Kalsel) adalah salah satu provinsi di Indonesia yang terletak di pulau Kalimantan. Ibu kotanya adalah Banjarmasin. Provinsi Kalimantan Selatan memiliki luas 37.530,52 km²[5] dengan populasi hampir 3,7 juta jiwa.\n" +
                    "Provinsi ini mempunyai 11 kabupaten dan 2 kota. DPRD Kalimantan Selatan dengan surat keputusan No. 2 Tahun 1989 tanggal 31 Mei 1989 menetapkan 14 Agustus 1950 sebagai Hari Jadi Provinsi Kalimantan Selatan. Tanggal 14 Agustus 1950 melalui Peraturan Pemerintah RIS No. 21 Tahun 1950, merupakan tanggal dibentuknya provinsi Kalimantan, setelah pembubaran Republik Indonesia Serikat (RIS), dengan gubernur Dokter Moerjani. Secara historis wilayah Kalimantan Selatan mula-mula dibentuk merupakan wilayah Karesidenan Kalimantan Selatan (dengan Residen Mohammad Hanafiah) di dalam Propinsi Kalimantan itu sendiri.\n",
            "Kalimantan Timur (disingkat Kaltim) adalah sebuah provinsi Indonesia di Pulau Kalimantan bagian ujung timur yang berbatasan dengan Malaysia, Kalimantan Utara, Kalimantan Tengah, Kalimantan Selatan, Kalimantan Barat, dan Sulawesi. Luas total Kaltim adalah 127.346,92 km² dan populasi sebesar 3.575.449 jiwa (2017).[1] Kaltim merupakan wilayah dengan kepadatan penduduk terendah keempat di nusantara. Ibu kota provinsi ini adalah kota Samarinda.\n",
            "Kalimantan Utara (disingkat Kaltara) adalah sebuah provinsi di Indonesia yang terletak di bagian utara Pulau Kalimantan. Provinsi ini berbatasan langsung dengan negara tetangga Malaysia, yaitu Negara Bagian Sabah dan Sarawak. Pusat pemerintahan Kalimantan Utara saat ini berada di kota Tanjung Selor, bersama dengan pusat pemerintahan Kabupaten Bulungan.\n",
            "Sulawesi Utara (disingkat Sulut) adalah salah satu provinsi yang terletak di ujung utara Pulau Sulawesi dengan ibu kota terletak di kota Manado. Sulawesi Utara atau Sulut berbatasan dengan Laut Maluku dan Samudera Pasifik di sebelah timur, Laut Maluku dan Teluk Tomini di sebelah selatan, Laut Sulawesi dan provinsi Gorontalo di sebelah barat, dan provinsi Davao del Sur (Filipina) di sebelah utara.",
            "Sulawesi Tengah (disingkat Sulteng) adalah sebuah provinsi di bagian tengah Pulau Sulawesi, Indonesia. Ibu kota provinsi ini adalah Kota Palu. Luas wilayahnya 61.841,29 km², dan jumlah penduduknya 3.222.241 jiwa (2015). Sulawesi Tengah memiliki wilayah terluas di antara semua provinsi di Pulau Sulawesi, dan memiliki jumlah penduduk terbanyak kedua di Pulau Sulawesi setelah provinsi Sulawesi Selatan. Gubernur yang menjabat sekarang adalah Drs. H. Longki Djanggola, M.Si. bersama dengan (Alm) Sudarto untuk periode kedua.\n",
            "Sulawesi Selatan (disingkat Sulsel) (Lontara: ᨔᨘᨒᨓᨙᨔᨗ ᨔᨒᨈ ) adalah sebuah provinsi di Indonesia yang terletak di bagian selatan Sulawesi. Ibu kotanya adalah Makassar.\n",
            "Sulawesi Tenggara (disingkat Sultra) merupakan sebuah provinsi di Indonesia yang terletak bagian tenggara pulau Sulawesi dengan ibu kota Kendari.\n" +
                    "Provinsi Sulawesi Tenggara terletak di Jazirah Tenggara Pulau Sulawesi, secara geografis terletak di bagian selatan garis khatulistiwa di antara 02°45' – 06°15' Lintang Selatan dan 120°45' – 124°30' Bujur Timur serta mempunyai wilayah daratan seluas 38.140 km² (3.814.000 ha) dan perairan (laut) seluas 110.000 km² (11.000.000 ha).\n",
            "Provinsi Gorontalo adalah salah satu Provinsi di Indonesia yang lahir pada tanggal 5 Desember, 2000[6] dan memiliki Ibu kota provinsi bernama sama yaitu, Kota Gorontalo. Sama halnya dengan ibu kotanya, Provinsi Gorontalo terkenal dengan julukan \"Serambi Madinah\". Dalam catatan sejarah Indonesia, satu-satunya Presiden RI yang berasal dari Suku Gorontalo adalah Presiden Republik Indonesia ke-3, Prof. DR. Ing. B.J. Habibie, dari garis keturunan ayahnya yang memiliki marga Habibie, yaitu Alwi Abdul Jalil Habibie.",
            "Sulawesi Barat (disingkat Sulbar) adalah sebuah provinsi di Indonesia yang terletak di bagian barat Sulawesi. Pembentukan Provinsi Sulawesi Barat telah diperjuangkan sejak tahun 1960. Pada masa itu pulau Sulawesi terdapat 3 (tiga) Provinsi yakni Provinsi Sulawesi Selatan, Provinsi Sulawesi Tengah dan Provinsi Sulawesi Utara. Namun, pada tahun 1963 Pemekaran Provinsi di pulau Sulawesi oleh pemerintah pusat adalah pembentukan Provinsi Sulawesi Tenggara. Usulan pembentukan Provinsi Sulawesi Barat tidak disetujui oleh Pemerintah Pusat.\n",
            "Maluku adalah sebuah provinsi yang meliputi bagian selatan Kepulauan Maluku, Indonesia. Lintasan sejarah Maluku telah dimulai sejak zaman kerajaan-kerajaan besar di Timur Tengah seperti kerajaan Mesir yang dipimpin Firaun. Bukti bahwa sejarah Maluku adalah yang tertua di Indonesia adalah catatan tablet tanah liat yang ditemukan di Persia, Mesopotamia, dan Mesir menyebutkan adanya negeri dari timur yang sangat kaya, merupakan tanah surga, dengan hasil alam berupa cengkih, emas dan mutiara, daerah itu tak lain dan tak bukan adalah tanah Maluku yang memang merupakan sentra penghasil Pala, Fuli, Cengkih dan Mutiara. Pala dan Fuli dengan mudah didapat dari Banda Kepulauan, Cengkih dengan mudah ditemui di negeri-negeri di Ambon, Pulau-Pulau Lease (Saparua, Haruku & Nusa laut) dan Nusa Ina serta Mutiara dihasilkan dalam jumlah yang cukup besar di Kota Dobo, Kepulauan Aru.\n",
            "Maluku Utara (disingkat Malut) adalah salah satu provinsi di Indonesia. Maluku Utara resmi terbentuk pada tanggal 4 Oktober 1999, melalui UU RI Nomor 46 Tahun 1999 dan UU RI Nomor 6 Tahun 2003. Sebelum resmi menjadi sebuah provinsi, Maluku Utara merupakan bagian dari Provinsi Maluku, yaitu Kabupaten Maluku Utara dan Kabupaten Halmahera Tengah.\n",
            "Papua adalah provinsi terluas Indonesia yang terletak di bagian tengah Pulau Papua atau bagian paling timur wilayah Papua milik Indonesia. Belahan timurnya merupakan negara Papua Nugini. Provinsi Papua sebelumnya bernama Irian Jaya yang mencakup seluruh wilayah Papua Bagian barat. Sejak tahun 2003, dibagi menjadi dua provinsi dengan bagian timur tetap memakai nama Papua sedangkan bagian baratnya memakai nama Papua Barat. Papua memiliki luas 808.105 km persegi dan merupakan pulau terbesar kedua di dunia dan terbesar pertama di Indonesia.\n",
            "Papua Barat (disingkat Pabar) adalah sebuah provinsi Indonesia yang terletak di ujung barat Pulau Papua. Ibu kotanya adalah Manokwari. Nama provinsi ini sebelumnya adalah Irian Jaya Barat yang ditetapkan dalam Undang-Undang Nomor 45 Tahun 1999. Berdasarkan Peraturan Pemerintah Nomor 24 Tahun 2007 tanggal 18 April 2007, nama provinsi ini diubah menjadi Papua Barat. Papua Barat dan Papua merupakan provinsi yang memperoleh status otonomi khusus. Provinsi Papua Barat, meski telah menjadi provinsi tersendiri, tetap mendapat perlakuan khusus sebagaimana provinsi induknya. Provinsi ini juga mempunyai KPUD sendiri dan menyelenggarakan pemilu untuk pertama kalinya pada tanggal 5 April 2004.\n"

    };
    public static String[] webDetail = {
            "https://id.wikipedia.org/wiki/Aceh",
            "https://id.wikipedia.org/wiki/Sumatra_Utara",
            "https://id.wikipedia.org/wiki/Sumatra_Barat",
            "https://id.wikipedia.org/wiki/Riau",
            "https://id.wikipedia.org/wiki/Jambi",
            "https://id.wikipedia.org/wiki/Sumatra_Selatan",
            "https://id.wikipedia.org/wiki/Bengkulu",
            "https://id.wikipedia.org/wiki/lampung",
            "https://id.wikipedia.org/wiki/Kepulauan_Bangka_Belitung",
            "https://id.wikipedia.org/wiki/Kepulauan_Riau",
            "https://id.wikipedia.org/wiki/Daerah_Khusus_Ibukota_Jakarta",
            "https://id.wikipedia.org/wiki/Jawa_Barat",
            "https://id.wikipedia.org/wiki/Jawa_Tengah",
            "https://id.wikipedia.org/wiki/Daerah_Istimewa_Yogyakarta",
            "https://id.wikipedia.org/wiki/Jawa_Timur",
            "https://id.wikipedia.org/wiki/Banten",
            "https://id.wikipedia.org/wiki/Bali",
            "https://id.wikipedia.org/wiki/Nusa_Tenggara_Timur",
            "https://id.wikipedia.org/wiki/Nusa_Tenggara_Barat",
            "https://id.wikipedia.org/wiki/Kalimantan_Barat",
            "https://id.wikipedia.org/wiki/Kalimantan_Tengah",
            "https://id.wikipedia.org/wiki/Kalimantan_Selatan",
            "https://id.wikipedia.org/wiki/Kalimantan_Timur",
            "https://id.wikipedia.org/wiki/Kalimantan_Utara",
            "https://id.wikipedia.org/wiki/Sulawesi_Utara",
            "https://id.wikipedia.org/wiki/Sulawesi_Tengah",
            "https://id.wikipedia.org/wiki/Sulawesi_Selatan",
            "https://id.wikipedia.org/wiki/Sulawesi_Tenggara",
            "https://id.wikipedia.org/wiki/Gorontalo",
            "https://id.wikipedia.org/wiki/Sulawesi_Barat",
            "https://id.wikipedia.org/wiki/Maluku",
            "https://id.wikipedia.org/wiki/Maluku_Utara",
            "https://id.wikipedia.org/wiki/Papua",
            "https://id.wikipedia.org/wiki/Papua_Barat"

    };
    private static String[] provinceName = {
            "Aceh",
            "Sumatra Utara",
            "Sumatra Barat",
            "Riau",
            "Jambi",
            "Sumatra Selatan",
            "Bengkulu",
            "Lampung",
            "Kepulauan Bangka Belitung",
            "Kepulauan Riau",
            "DKI Jakarta",
            "Jawa barat",
            "Jawa Tengah",
            "DI Yogyakarta",
            "Jawa Timur",
            "Banten",
            "Bali",
            "Nusa tenggara Timur",
            "Nusa tenggara Barat",
            "Kalimantan Barat",
            "kalimantan Tengah",
            "kalimantan Selatan",
            "Kalimantan Timur",
            "kalimantan Utara",
            "Sulawesi Utara",
            "Sulawesi tengah",
            "Sulawesi Selatan",
            "Sulawesi tenggara",
            "Gorontalo",
            "Sulawesi Barat",
            "Maluku",
            "Maluku Utara",
            "Papua",
            "Papua Barat",
    };
    private static String[] ibuKota = {
            "Banda Aceh",
            "Medan",
            "Padang",
            "Pekan Baru",
            "Jambi",
            "palembang",
            "Bengkulu",
            "Bandar lampung",
            "Pangkalpinang",
            "Tanjungpinang",
            "Jakarta",
            "Bandung",
            "Semarang",
            "Yogyakarta",
            "Surabaya",
            "Serang",
            "Denpasar",
            "Kupang",
            "Mataram",
            "Pontianak",
            "Palangka Raya",
            "Banjarmasin",
            "Samarinda",
            "Tanjung Selor",
            "Manado",
            "Palu",
            "Makassar",
            "Kendari",
            "Gorontalo",
            "Mamuju",
            "Ambon",
            "Sofifi",
            "Jayapura",
            "Manokwari"
    };
    private static int[] provinceLogos = {
            R.drawable.img_01_provinsi_nanggro_aceh_darussalam,
            R.drawable.img_02_provinsi_sumatera_utara,
            R.drawable.img_03_provinsi_sumatera_barat,
            R.drawable.img_04_provinsi_riau,
            R.drawable.img_05_provinsi_jambi,
            R.drawable.img_06_provinsi_sumatera_selatan,
            R.drawable.img_07_provinsi_bengkulu,
            R.drawable.img_08_provinsi_lampung,
            R.drawable.img_09_provinsi_bangka_belitung,
            R.drawable.img_10_provinsi_kepulauan_riau,
            R.drawable.img_11_provinsi_dki_jakarta,
            R.drawable.img_12_provinsi_jawa_barat,
            R.drawable.img_13_provinsi_jawa_tengah,
            R.drawable.img_14_provinsi_daerah_istimewa_yogyakarta,
            R.drawable.img_15_provinsi_jawa_timur,
            R.drawable.img_16_provinsi_banten,
            R.drawable.img_17_provinsi_bali,
            R.drawable.img_18_provinsi_nusa_tenggara_timur,
            R.drawable.img_19_provinsi_nusa_tenggara_barat,
            R.drawable.img_20_provinsi_kalimantan_barat,
            R.drawable.img_21_provinsi_kalimantan_tengah,
            R.drawable.img_22_provinsi_kalimantan_selatan,
            R.drawable.img_23_provinsi_kalimantan_timur,
            R.drawable.img_24_provinsi_kalimantan_utara,
            R.drawable.img_25_provinsi_sulawesi_utara,
            R.drawable.img_26_provinsi_sulawesi_tengah,
            R.drawable.img_27_provinsi_sulawesi_selatan,
            R.drawable.img_28_provinsi_sulawesi_tenggara,
            R.drawable.img_29_provinsi_gorontalo,
            R.drawable.img_30_provinsi_sulawesi_barat,
            R.drawable.img_31_provinsi_maluku,
            R.drawable.img_32_provinsi_maluku_utara,
            R.drawable.img_33_provinsi_papua,
            R.drawable.img_34_provinsi_papua_barat


    };
    private static int[] jmlPenduduk = {
            254904,
            2229408,
            914968,
            1064566,
            583487,
            1602071,
            359488,
            997728,
            200326,
            204735,
            10177924,
            2490622,
            1602717,
            417744,
            2862406,
            643205,
            897300,
            459314,
            402286,
            618388,
            331115,
            684183,
            812597,
            49242,
            427906,
            374020,
            1469601,
            359371,
            195468,
            138698,
            427934,
            1783,
            288786,
            162578

    };
    private static int[] luasWil = {
            6136,
            2651,
            69493,
            63226,
            20558,
            40061,
            1517,
            19722,
            11841,
            15086,
            66233,
            16731,
            3737,
            325,
            32681,
            26674,
            12778,
            613,
            18027,
            10782,
            267851,
            7267,
            718,
            67777,
            15726,
            39506,
            17577,
            29589,
            6596,
            506419,
            35945,
            2098,
            940,
            318628
    };
    private static int[] jmlKabupaten = {
            8,
            28,
            12,
            10,
            9,
            13,
            9,
            13,
            6,
            5,
            1,
            18,
            29,
            4,
            29,
            4,
            4,
            21,
            8,
            12,
            13,
            11,
            7,
            4,
            11,
            12,
            21,
            15,
            5,
            6,
            9,
            8,
            28,
            12

    };

    static ArrayList<Province> getListData() {
        ArrayList<Province> list = new ArrayList<>();
        for (int position = 0; position < provinceName.length; position++) {
            Province province = new Province();
            province.setProvince_name(provinceName[position]);
            province.setKota(ibuKota[position]);
            province.setLogo(provinceLogos[position]);
            list.add(province);
            province.setJumlahPenduduk(jmlPenduduk[position]);
            province.setLuasWil(luasWil[position]);
            province.setJml_kabupaten(jmlKabupaten[position]);
            province.setJml_kota(jmlKota[position]);
            province.setDetail(provinceDetails[position]);
            province.setWebDetail(webDetail[position]);
        }
        return list;
    }


}
